version: '3.9'

services:
  backend:
    image: soham008/edutrack-backend:latest
    container_name: edutrack-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped
    networks:
      - edutrack-network

  frontend:
    image: soham008/edutrack-frontend:latest
    container_name: edutrack-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - edutrack-network

networks:
  edutrack-network:
    driver: bridge